import { Component, OnInit } from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { AuthenticationService } from '../authentication.service';
@Component({
  selector: 'app-view-details',
  templateUrl: './view-details.component.html',
  styleUrls: ['./view-details.component.css']
})
export class ViewDetailsComponent implements OnInit {


  id;
  _id;
  sampleData = {
    "code": "OK",
    "message": "Record Fetch Completed",
    "portfolioResponse": [
      {
        "projectId": "BFSI-App Moderanization-DTCC-Dinesh-App Moderanization-4",
        "bu": "BFSI",
        "vertical": "App Moderanization",
        "account": "DTCC",
        "bo": "Dinesh",
        "al": "test@wipro.com",
        "appName": "App Moderanization-4",
        "asIs": {
          "ageOfApplication": "4 years",
          "aplicationLanguageDependecny": "Jackon",
          "applicactionDocumentsAvailability": "yes",
          "applicationClassification": "This will hold App classification",
          "applicationDescription": "This app preserves legal Entitiessss",
          "applicationSupportHours": "24/7",
          "appServers": "WebSphere",
          "appVersion": "9.0",
          "backEndStack": "Oracle",
          "businessUnitDiscoverySpoc": "test1@wipro.com",
          "changeRequestYearly": "10",
          "cicd": "Jenkins",
          "cicdProcess": "yes",
          "database": "Oracle",
          "databaseVersion": "8.3",
          "frontEndStack": "Node JS",
          "globalLocal": "Global",
          "incidentRequestYearly": "30",
          "infrastructure": "On-Premise",
          "isApplicationPlannedSunset": "no",
          "isApplicationRationalized": "yes",
          "isApplicationTobeOnCloud": "no",
          "isAppShadowIT": "no",
          "isOnSupportPresent": "yes",
          "langageBackEnd": "PL/SQL",
          "langaugeFrontEnd": "Angular",
          "langaugeVersion": "8.0",
          "operatingSystem": "Windows 2012",
          "packageSoftware": "Java Spring Boot",
          "platform": "AWS",
          "process": "Agile",
          "processTools": "Jira",
          "region": "South-1",
          "regionalDiscoverySpoc": "test2Wwipro.com",
          "releaseCycle": "Monthly",
          "serviceRequestYearly": "20",
          "solutionModel": "Inhouse",
          "version": "3.0"
        },
        "toBe": {
          "platform": "aws,azure,on-premisessssss",
          "database": "DynamoDB,Oracle",
          "analytics": "analytics",
          "streaming": "kafka",
          "messaging": "Rabbit MQ",
          "serverless": "Lamda",
          "integration": "Mulesoft",
          "schemaDefinition": "raml",
          "imageBuild": "Fabric8",
          "cicd": "Jenkins",
          "containerOrchestration": "Kubernetes, Docker",
          "serviceDiscovery": "Netflix",
          "rpc": "rest,gRPC",
          "serviceMesh": "Istio",
          "apiGateway": "Amazon",
          "hostManagement": "terraform",
          "containerRegistry": "JFRog",
          "security": "JWT,OpenID,SAML",
          "keyManagement": "keycloak",
          "memoryManagement": "redis",
          "monitoring": "prometesis,cloudwatch",
          "logging": "log4j",
          "tracing": "zipkin",
          "apiAnalytics": "apigee",
          "alerts": "aws"
        }
      },
      {
        "projectId": "BFSI-App Moderanization-DTCC-Dinesh-App Moderanization",
        "bu": "BFSI",
        "vertical": "App Moderanization",
        "account": "DTCC",
        "bo": "Dinesh",
        "al": "test@wipro.com",
        "appName": "App Moderanization",
        "asIs": {
          "ageOfApplication": "4 years",
          "aplicationLanguageDependecny": "Jackon",
          "applicactionDocumentsAvailability": "yes",
          "applicationClassification": "This will hold App classification",
          "applicationDescription": "This app preserves legal Entitiessss",
          "applicationSupportHours": "24/7",
          "appServers": "WebSphere",
          "appVersion": "9.0",
          "backEndStack": "Oracle",
          "businessUnitDiscoverySpoc": "test1@wipro.com",
          "changeRequestYearly": "10",
          "cicd": "Jenkins",
          "cicdProcess": "yes",
          "database": "Oracle",
          "databaseVersion": "8.3",
          "frontEndStack": "Node JS",
          "globalLocal": "Global",
          "incidentRequestYearly": "30",
          "infrastructure": "On-Premise",
          "isApplicationPlannedSunset": "no",
          "isApplicationRationalized": "yes",
          "isApplicationTobeOnCloud": "no",
          "isAppShadowIT": "no",
          "isOnSupportPresent": "yes",
          "langageBackEnd": "PL/SQL",
          "langaugeFrontEnd": "Angular",
          "langaugeVersion": "8.0",
          "operatingSystem": "Windows 2012",
          "packageSoftware": "Java Spring Boot",
          "platform": "AWS",
          "process": "Agile",
          "processTools": "Jira",
          "region": "South-1",
          "regionalDiscoverySpoc": "test2Wwipro.com",
          "releaseCycle": "Monthly",
          "serviceRequestYearly": "20",
          "solutionModel": "Inhouse",
          "version": "3.0"
        },
        "toBe": {
          "platform": "aws,azure,on-premisessssss",
          "database": "DynamoDB,Oracle",
          "analytics": "analytics",
          "streaming": "kafka",
          "messaging": "Rabbit MQ",
          "serverless": "Lamda",
          "integration": "Mulesoft",
          "schemaDefinition": "raml",
          "imageBuild": "Fabric8",
          "cicd": "Jenkins",
          "containerOrchestration": "Kubernetes, Docker",
          "serviceDiscovery": "Netflix",
          "rpc": "rest,gRPC",
          "serviceMesh": "Istio",
          "apiGateway": "Amazon",
          "hostManagement": "terraform",
          "containerRegistry": "JFRog",
          "security": "JWT,OpenID,SAML",
          "keyManagement": "keycloak",
          "memoryManagement": "redis",
          "monitoring": "prometesis,cloudwatch",
          "logging": "log4j",
          "tracing": "zipkin",
          "apiAnalytics": "apigee",
          "alerts": "aws"
        }
      },
      {
        "projectId": "BFSI-App Moderanization-DTCC-Dinesh-App Moderanization-6",
        "bu": "BFSI",
        "vertical": "App Moderanization",
        "account": "DTCC",
        "bo": "Dinesh",
        "al": "test@wipro.com",
        "appName": "App Moderanization-6",
        "asIs": {
          "ageOfApplication": "4 years",
          "aplicationLanguageDependecny": "Jackon",
          "applicactionDocumentsAvailability": "yes",
          "applicationClassification": "This will hold App classification",
          "applicationDescription": "This app preserves legal Entitiessss",
          "applicationSupportHours": "24/7",
          "appServers": "WebSphere",
          "appVersion": "9.0",
          "backEndStack": "Oracle",
          "businessUnitDiscoverySpoc": "test1@wipro.com",
          "changeRequestYearly": "10",
          "cicd": "Jenkins",
          "cicdProcess": "yes",
          "database": "Oracle",
          "databaseVersion": "8.3",
          "frontEndStack": "Node JS",
          "globalLocal": "Global",
          "incidentRequestYearly": "30",
          "infrastructure": "On-Premise",
          "isApplicationPlannedSunset": "no",
          "isApplicationRationalized": "yes",
          "isApplicationTobeOnCloud": "no",
          "isAppShadowIT": "no",
          "isOnSupportPresent": "yes",
          "langageBackEnd": "PL/SQL",
          "langaugeFrontEnd": "Angular",
          "langaugeVersion": "8.0",
          "operatingSystem": "Windows 2012",
          "packageSoftware": "Java Spring Boot",
          "platform": "AWS",
          "process": "Agile",
          "processTools": "Jira",
          "region": "South-1",
          "regionalDiscoverySpoc": "test2Wwipro.com",
          "releaseCycle": "Monthly",
          "serviceRequestYearly": "20",
          "solutionModel": "Inhouse",
          "version": "3.0"
        },
        "toBe": {
          "platform": "{aws,azure,on-premisessssss",
          "database": "DynamoDB,Oracle",
          "analytics": "analytics",
          "streaming": "kafka",
          "messaging": "Rabbit MQ",
          "serverless": "Lamda",
          "integration": "Mulesoft",
          "schemaDefinition": "raml",
          "imageBuild": "Fabric8",
          "cicd": "Jenkins",
          "containerOrchestration": "Kubernetes, Docker",
          "serviceDiscovery": "Netflix",
          "rpc": "rest,gRPC",
          "serviceMesh": "Istio",
          "apiGateway": "Amazon",
          "hostManagement": "terraform",
          "containerRegistry": "JFRog",
          "security": "JWT,OpenID,SAML",
          "keyManagement": "keycloak",
          "memoryManagement": "redis",
          "monitoring": "prometesis,cloudwatch",
          "logging": "log4j",
          "tracing": "zipkin",
          "apiAnalytics": "apigee",
          "alerts": "aws"
        }
      },
      {
        "projectId": "ENU-App Moderanization-DTCC-Dinesh-App Moderanization-6",
        "bu": "ENU",
        "vertical": "App Moderanization",
        "account": "DTCC",
        "bo": "Dinesh",
        "al": "test@wipro.com",
        "appName": "App Moderanization-6",
        "asIs": {
          "ageOfApplication": "4 years",
          "aplicationLanguageDependecny": "Jackon",
          "applicactionDocumentsAvailability": "yes",
          "applicationClassification": "This will hold App classification",
          "applicationDescription": "This app preserves legal Entitiessss",
          "applicationSupportHours": "24/7",
          "appServers": "WebSphere",
          "appVersion": "9.0",
          "backEndStack": "Oracle",
          "businessUnitDiscoverySpoc": "test1@wipro.com",
          "changeRequestYearly": "10",
          "cicd": "Jenkins",
          "cicdProcess": "yes",
          "database": "Oracle",
          "databaseVersion": "8.3",
          "frontEndStack": "Node JS",
          "globalLocal": "Global",
          "incidentRequestYearly": "30",
          "infrastructure": "On-Premise",
          "isApplicationPlannedSunset": "no",
          "isApplicationRationalized": "yes",
          "isApplicationTobeOnCloud": "no",
          "isAppShadowIT": "no",
          "isOnSupportPresent": "yes",
          "langageBackEnd": "PL/SQL",
          "langaugeFrontEnd": "Angular",
          "langaugeVersion": "8.0",
          "operatingSystem": "Windows 2012",
          "packageSoftware": "Java Spring Boot",
          "platform": "AWS",
          "process": "Agile",
          "processTools": "Jira",
          "region": "South-1",
          "regionalDiscoverySpoc": "test2Wwipro.com",
          "releaseCycle": "Monthly",
          "serviceRequestYearly": "20",
          "solutionModel": "Inhouse",
          "version": "3.0"
        },
        "toBe": {
          "platform": "{aws,azure,on-premisessssss",
          "database": "DynamoDB,Oracle",
          "analytics": "analytics",
          "streaming": "kafka",
          "messaging": "Rabbit MQ",
          "serverless": "Lamda",
          "integration": "Mulesoft",
          "schemaDefinition": "raml",
          "imageBuild": "Fabric8",
          "cicd": "Jenkins",
          "containerOrchestration": "Kubernetes, Docker",
          "serviceDiscovery": "Netflix",
          "rpc": "rest,gRPC",
          "serviceMesh": "Istio",
          "apiGateway": "Amazon",
          "hostManagement": "terraform",
          "containerRegistry": "JFRog",
          "security": "JWT,OpenID,SAML",
          "keyManagement": "keycloak",
          "memoryManagement": "redis",
          "monitoring": "prometesis,cloudwatch",
          "logging": "log4j",
          "tracing": "zipkin",
          "apiAnalytics": "apigee",
          "alerts": "aws"
        }
      },
      {
        "projectId": "BFSI-App Moderanization-DTCC-Dinesh-App Moderanization-3",
        "bu": "BFSI",
        "vertical": "App Moderanization",
        "account": "DTCC",
        "bo": "Dinesh",
        "al": "test@wipro.com",
        "appName": "App Moderanization-3",
        "asIs": {
          "ageOfApplication": "4 years",
          "aplicationLanguageDependecny": "Jackon",
          "applicactionDocumentsAvailability": "yes",
          "applicationClassification": "This will hold App classification",
          "applicationDescription": "This app preserves legal Entitiessss",
          "applicationSupportHours": "24/7",
          "appServers": "WebSphere",
          "appVersion": "9.0",
          "backEndStack": "Oracle",
          "businessUnitDiscoverySpoc": "test1@wipro.com",
          "changeRequestYearly": "10",
          "cicd": "Jenkins",
          "cicdProcess": "yes",
          "database": "Oracle",
          "databaseVersion": "8.3",
          "frontEndStack": "Node JS",
          "globalLocal": "Global",
          "incidentRequestYearly": "30",
          "infrastructure": "On-Premise",
          "isApplicationPlannedSunset": "no",
          "isApplicationRationalized": "yes",
          "isApplicationTobeOnCloud": "no",
          "isAppShadowIT": "no",
          "isOnSupportPresent": "yes",
          "langageBackEnd": "PL/SQL",
          "langaugeFrontEnd": "Angular",
          "langaugeVersion": "8.0",
          "operatingSystem": "Windows 2012",
          "packageSoftware": "Java Spring Boot",
          "platform": "AWS",
          "process": "Agile",
          "processTools": "Jira",
          "region": "South-1",
          "regionalDiscoverySpoc": "test2Wwipro.com",
          "releaseCycle": "Monthly",
          "serviceRequestYearly": "20",
          "solutionModel": "Inhouse",
          "version": "3.0"
        },
        "toBe": {
          "platform": "aws,azure,on-premisessssss",
          "database": "DynamoDB,Oracle",
          "analytics": "analytics",
          "streaming": "kafka",
          "messaging": "Rabbit MQ",
          "serverless": "Lamda",
          "integration": "Mulesoft",
          "schemaDefinition": "raml",
          "imageBuild": "Fabric8",
          "cicd": "Jenkins",
          "containerOrchestration": "Kubernetes, Docker",
          "serviceDiscovery": "Netflix",
          "rpc": "rest,gRPC",
          "serviceMesh": "Istio",
          "apiGateway": "Amazon",
          "hostManagement": "terraform",
          "containerRegistry": "JFRog",
          "security": "JWT,OpenID,SAML",
          "keyManagement": "keycloak",
          "memoryManagement": "redis",
          "monitoring": "prometesis,cloudwatch",
          "logging": "log4j",
          "tracing": "zipkin",
          "apiAnalytics": "apigee",
          "alerts": "aws"
        }
      },
      {
        "projectId": "ENU-App Moderanization-DTCC-Dinesh-App Moderanization-7",
        "bu": "ENU",
        "vertical": "App Moderanization",
        "account": "DTCC",
        "bo": "Dinesh",
        "al": "test@wipro.com",
        "appName": "App Moderanization-7",
        "asIs": {
          "ageOfApplication": "4 years",
          "aplicationLanguageDependecny": "Jackon",
          "applicactionDocumentsAvailability": "yes",
          "applicationClassification": "This will hold App classification",
          "applicationDescription": "This app preserves legal Entitiessss",
          "applicationSupportHours": "24/7",
          "appServers": "WebSphere",
          "appVersion": "9.0",
          "backEndStack": "Oracle",
          "businessUnitDiscoverySpoc": "test1@wipro.com",
          "changeRequestYearly": "10",
          "cicd": "Jenkins",
          "cicdProcess": "yes",
          "database": "Oracle",
          "databaseVersion": "8.3",
          "frontEndStack": "Node JS",
          "globalLocal": "Global",
          "incidentRequestYearly": "30",
          "infrastructure": "On-Premise",
          "isApplicationPlannedSunset": "no",
          "isApplicationRationalized": "yes",
          "isApplicationTobeOnCloud": "no",
          "isAppShadowIT": "no",
          "isOnSupportPresent": "yes",
          "langageBackEnd": "PL/SQL",
          "langaugeFrontEnd": "Angular",
          "langaugeVersion": "8.0",
          "operatingSystem": "Windows 2012",
          "packageSoftware": "Java Spring Boot",
          "platform": "AWS",
          "process": "Agile",
          "processTools": "Jira",
          "region": "South-1",
          "regionalDiscoverySpoc": "test2Wwipro.com",
          "releaseCycle": "Monthly",
          "serviceRequestYearly": "20",
          "solutionModel": "Inhouse",
          "version": "3.0"
        },
        "toBe": {
          "platform": "{aws,azure,on-premisessssss",
          "database": "DynamoDB,Oracle",
          "analytics": "analytics",
          "streaming": "kafka",
          "messaging": "Rabbit MQ",
          "serverless": "Lamda",
          "integration": "Mulesoft",
          "schemaDefinition": "raml",
          "imageBuild": "Fabric8",
          "cicd": "Jenkins",
          "containerOrchestration": "Kubernetes, Docker",
          "serviceDiscovery": "Netflix",
          "rpc": "rest,gRPC",
          "serviceMesh": "Istio",
          "apiGateway": "Amazon",
          "hostManagement": "terraform",
          "containerRegistry": "JFRog",
          "security": "JWT,OpenID,SAML",
          "keyManagement": "keycloak",
          "memoryManagement": "redis",
          "monitoring": "prometesis,cloudwatch",
          "logging": "log4j",
          "tracing": "zipkin",
          "apiAnalytics": "apigee",
          "alerts": "aws"
        }
      }
    ]
  }


  constructor() { }

  ngOnInit() {
  }

  testID: string;
  collapsible(id) {
    this.testID = id;
  }
  retriveData(data) {

    this.id = data.projectId;

  }
  deleteData(data) {
    this._id = data.projectId;

  }

}
